name: Playdate-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

- name: Install Playdate SDK
  id: playdate
  uses: pd-rs/get-playdate-sdk@0.1.2

- name: usage
  run: |
    echo "SDK root: $PLAYDATE_SDK_PATH"
    echo "SDK root: ${{ steps.playdate.outputs.root }}"
    echo "SDK version: ${{ steps.playdate.outputs.version }}"
    pdc --version

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: pd-rs/get-playdate-sdk@0.1.2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./build.sh
